/* eslint-disable react/prop-types */
import RightArrow from "../../../assets/AdminDashboard/RightArrow.svg";
import pdfIcon from "../../../assets/AdminDashboard/pdfIcon.svg";

const InvoicingTable = ({ isDark, leftArrow  }) => {
    return (
        <>
            <div className="h-full overflow-x-auto">
                <table className="w-full border-collapse overflow-x-auto">
                    <thead className="overflow-x-auto">
                        <tr>
                            <th className={`py-2 px-4 mid-sm:text-[16px] text-[14px] ${isDark ? 'bg-gray-100' : 'text-[#272c35]'} font-semibold text-left`}>
                                Generated By
                            </th>
                            <th className={`py-2 px-4 mid-sm:text-[16px] text-[14px] ${isDark ? 'bg-gray-100' : 'text-[#272c35]'} font-semibold text-left`}>
                                Send To
                            </th>
                            <th className={`py-2 px-4 mid-sm:text-[16px] text-[14px]  ${isDark ? 'bg-gray-100' : 'text-[#272c35]'} font-semibold text-left`}>
                                Full Name
                            </th>
                            <th className={`py-2 px-4 mid-sm:text-[16px] text-[14px]  ${isDark ? 'bg-gray-100' : 'text-[#272c35]'} font-semibold text-left`}>
                                Send Date
                            </th>
                            <th className={`py-2 px-4 mid-sm:text-[16px] text-[14px]  ${isDark ? 'bg-gray-100' : 'text-[#272c35]'} font-semibold text-left`}>
                                Price
                            </th>
                            <th className={`py-2 px-4 mid-sm:text-[16px] text-[14px]  ${isDark ? 'bg-gray-100' : 'text-[#272c35]'} font-semibold text-left`}>
                                Invoice Ref Number
                            </th>
                            <th className={`py-2 px-4 mid-sm:text-[16px] text-[14px]  ${isDark ? 'bg-gray-100' : 'text-[#272c35]'} font-semibold text-left`}>
                                Status
                            </th>
                            <th className={`py-2 px-4 mid-sm:text-[16px] text-[14px]  ${isDark ? 'bg-gray-100' : 'text-[#272c35]'} font-semibold text-left`}>
                                Product Description
                            </th>
                            <th className={`py-2 px-4 mid-sm:text-[16px] text-[14px]  ${isDark ? 'bg-gray-100' : 'text-[#272c35]'} font-semibold text-left`}>
                                PDF
                            </th>
                        </tr>
                    </thead>

                    <tbody className="overflow-x-auto">

                        <tr className="border text-left overflow-x-auto">
                            <td className={"py-2 px-4 " + (isDark ? "text-white" : "text-black")}>Nickname</td>
                            <td className={"py-2 px-4 " + (isDark ? "text-white" : "text-black")}>user@tesst.com</td>
                            <td className={"py-2 px-4 " + (isDark ? "text-white" : "text-black")}>User Test</td>
                            <td className={"py-2 px-4 " + (isDark ? "text-white" : "text-black")}>12.12.23</td>
                            <td className={"py-2 px-4 " + (isDark ? "text-white" : "text-black")}>£340.00</td>
                            <td className={"py-2 px-4 " + (isDark ? "text-white" : "text-black")}>RFLT000001</td>
                            <td className={"py-2 px-4 " + (isDark ? "text-white" : "text-black")}>
                                <select className={isDark ? "bg-black text-white" : "bg-white text-black"} name="" id="">
                                    <option value="Sent">Sent</option>
                                    <option value="Paid">Paid</option>
                                    <option value="Overdue">Overdue</option>
                                    <option value="Void">Void</option>
                                    <option value="Refunded">Refunded</option>
                                </select>
                            </td>
                            <td className={"py-2 px-4 " + (isDark ? "text-white" : "text-black")}>Rolex name and descrption </td>
                            <td className={"py-2 px-4 " + (isDark ? "text-white" : "text-black")}>
                                <img src={pdfIcon} alt="" className="h-10 w-10 mx-auto object-contain" />
                                <span className="cursor-pointer hover:underline">View</span>/
                                <span className="cursor-pointer hover:underline">Download</span>
                            </td>
                        </tr>

                    </tbody>
                </table>

            </div>

            <div className="mt-4 flex justify-center gap-3">
                <button

                    className={` hover:bg-[#000] border hover:border-[#fff] font-semibold py-1 px-2 rounded-l`}
                >
                    <img src={leftArrow} alt="" />
                </button>
                <ul className="pagination flex gap-3">
                    {Array.from({
                        length: 5,
                    }).map((_, index) => (
                        <li key={index}>
                            <button

                                className={`hover:bg-[#000]  border hover:border-[#fff] bg-gray-400 rounded-full hover:text-white font-semibold py-1 px-3 h-10 w-10`}
                            >
                                {index + 1}
                            </button>
                        </li>
                    ))}
                </ul>
                <button

                    className={` hover:bg-[#000]  border hover:border-[#fff]  font-semibold py-1 px-2 rounded-r`}
                >
                    <img src={RightArrow} alt="" />
                </button>
            </div>

        </>
    )
}

export default InvoicingTable